# Generated by Django 4.1 on 2022-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_todolist',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item_todolist',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item_todolist',
            name='title',
            field=models.TextField(),
        ),
    ]
